### PR TITLE
Fix type mismatch in `tsDefinition.mappings` between `airtable-ts` and `airtable-ts-formula`

### LINKED ISSUE #4: Type errors
types:
```ts
import type { Item, Table } from 'airtable-ts';

export interface User extends Item {
	id: string;
	slackId: string | null; // Original field: "Slack ID"
	accessToken: string | null; // Original field: "Access Token"
	sessions: string[]; // Original field: "Sessions"
}

export const usersTable: Table<User> = {
	name: 'Users',
	baseId: 'appQ1C7ZPxo88BdYB',
	tableId: 'tbl6Pqzztd03P0dJ7',
	mappings: {
		slackId: 'fld0UYevtZ3pPSlHm', // Original field: "Slack ID"
		accessToken: 'fldHltT3ZmI4LMxQL', // Original field: "Access Token"
		sessions: 'fldP9eGf8RRmBLy7i' // Original field: "Sessions"
	},
	schema: {
		slackId: 'string | null',
		accessToken: 'string | null',
		sessions: 'string[]'
	}
};

```

code:
```ts
const table = await pool.table(schema.usersTable);
const airtableFormula = formula(table, ['AND']);
await pool.scan(schema.usersTable, {
	filterByFormula: airtableFormula
});
```

error on the second line for `code`
```
[{
	"resource": "/home/koeg/men/hacker_man/projects/overdrive/src/routes/+layout.server.ts",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type 'import(\"/home/koeg/men/hacker_man/projects/overdrive/node_modules/airtable-ts/dist/types\").AirtableTsTable<import(\"/home/koeg/men/hacker_man/projects/overdrive/src/lib/server/airtable-schema\").User>' is not assignable to parameter of type 'import(\"/home/koeg/men/hacker_man/projects/overdrive/node_modules/airtable-ts-formula/dist/index\").AirtableTsTable<import(\"/home/koeg/men/hacker_man/projects/overdrive/src/lib/server/airtable-schema\").User>'.\n  The types of 'tsDefinition.mappings' are incompatible between these types.\n    Type '{ slackId: string; accessToken: string; sessions: string | string[]; } | undefined' is not assignable to type '{ slackId: string; accessToken: string; sessions: string; } | undefined'.\n      Type '{ slackId: string; accessToken: string; sessions: string | string[]; }' is not assignable to type '{ slackId: string; accessToken: string; sessions: string; }'.\n        Types of property 'sessions' are incompatible.\n          Type 'string | string[]' is not assignable to type 'string'.\n            Type 'string[]' is not assignable to type 'string'.",
	"source": "ts",
	"startLineNumber": 42,
	"startColumn": 34,
	"endLineNumber": 42,
	"endColumn": 39,
	"origin": "extHost1"
}]
```

### PR DESCRIPTION
**Pull request by kristianhalte**
This PR resolves #4, which was caused by a type inconsistency between **airtable-ts** and **airtable-ts-formula** for the `tsDefinition.mappings` field on the `AirtableTsTable` type.

* In **airtable-ts**, `mappings` is defined as:

  ```ts
  mappings?: { [k in keyof Omit<T, 'id'>]: MappingValue<T[k]> };
  ```

  where `MappingValue<T>` allows `string | string[]` for array fields.

* In **airtable-ts-formula**, `mappings` was previously defined more narrowly as:

  ```ts
  mappings?: { [k in keyof Omit<T, 'id'>]: string };
  ```

  which incorrectly restricted array field mappings to `string` only.

This PR updates the type definition in **airtable-ts-formula** by reusing the definitiuons from **airtable-ts**, ensuring that array fields correctly accept both `string` and `string[]` mapping values.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -1,28 +1,10 @@
 import {
 	type Formula as FormulatorFormula, compile,
 } from '@qualifyze/airtable-formulator';
+import {type AirtableTsTable, type Item} from 'airtable-ts';
```
Comment (domdomegg) [inline src/index.ts]: If we import this we have to add it as a dependency in package.json

File: src/index.ts [hunk 2]
```diff
@@ -1,28 +1,10 @@
...
-	fields: {
-		id: string;
-		name: string;
-	}[];
-	tsDefinition?: {
-		schema: {
-			[k in keyof Omit<T, 'id'>]: string;
-		};
-		mappings?: {
-			[k in keyof Omit<T, 'id'>]: string;
```
Comment (domdomegg) [inline src/index.ts:21]: Could we maybe instead support `string | string[]` here

**Review by domdomegg — CHANGES_REQUESTED** [review]
Thanks for the contribution! As per other comments.

Alternatively I was thinking of dropping the array mapping support in airtable-ts and cutting a new major version: I think it's confusing and not really necessary. That might be a cleaner solution to all of this.

File: src/index.ts (hunk 1 above)
Comment (kristianhalte) [reply src/index.ts]: True - I just thought it would be easier for you as a maintainer to reuse the type definition :)

File: src/index.ts (hunk 2 above)
Comment (kristianhalte) [reply src/index.ts:21]: That should work as well

**Review by domdomegg — APPROVED** [review]
Thanks!

**Comment by domdomegg** [comment]
Thanks for the contribution here, and sorry for the delays reviewing this PR - had some recent travels.

Published to NPM in version 1.1.0 🚀

**Comment by kristianhalte** [comment]
@domdomegg - just pulled the latest version 1.1.0, but it seems like the changes weren't published to NPM. Not sure if something broke in the CI/CD pipeline?

**Comment by domdomegg** [comment]
Good catch, and sorry about that - yeah I messed something up in the CI/CD pipeline. Released 1.1.1 which should actually have this in - have checked at https://www.npmjs.com/package/airtable-ts-formula?activeTab=code and looks like it's there now.
